### PR TITLE
fix: parse JSON in a specific function

### LINKED ISSUE #20: commit message containing double quotes breaks git -> json conversion
The following command:
```sh
git log -1 --pretty=format:'{"sha":"%H","author":"%aN<%aE>","date":"%aD","message":"%s"}' origin/test/commit-with-double-quotes
```
generates the following output:
returns:
```json
{
    "sha":"d4afa862921dec6963e7d6895538219a7525036e",
    "author":"oklinov<oklinov@tutanota.com>",
    "date":"Mon, 8 Sep 2025 09:38:49 +0200",
    "message":"test: commit with double quotes: ""
}
```

which is an invalid json. We need to somehow escape the quotes.

### PR DESCRIPTION
**Pull request by ruocco-l**
Closes #20 

---

@kazadoiyul , I'll merge the changes from the comments by @oklinov and then set this to review but if you want you can already have a look

### CODE REVIEW

File: bin/utils.ts [hunk 1]
```diff
@@ -86,6 +87,19 @@ export const getHeadCommitSha = (githubEvent: GitHubEvent) => {
         : githubEvent.head_commit.id;
 };
 
+export const parseCommitAsJson = (commitString: string): Commit => {
```
Comment (oklinov) [inline bin/utils.ts]: I'd move this to `git.ts` as it's related only to git

File: bin/git.ts [hunk 2]
```diff
@@ -1,11 +1,12 @@
 import { Commit, Config } from './types';
-import { spawnCommandInGhWorkspace } from './utils.js';
+import { parseCommitAsJson, spawnCommandInGhWorkspace } from './utils.js';
 
-const GIT_LOG_FORMAT = `{"sha":"%H","author":"%aN<%aE>","date":"%aD","message":"%s"}`;
+const GIT_LOG_FORMAT = `%H»¦«%aN<%aE>»¦«%aD»¦«%s`;
```
Comment (oklinov) [inline bin/git.ts]: I'd create a const `GIT_FORMAT_SEPARATOR = '»¦«'` so it's defined only once and then define `GIT_LOG_FORMAT` as:
```suggestion
const GIT_LOG_FORMAT = ['%H', '%aN<%aE>', '%aD', '%s'].join(GIT_FORMAT_SEPARATOR);
```

though I might be less readible this way...I'll leave it up to you :slightly_smiling_face:

File: bin/git.ts [hunk 3]
```diff
@@ -37,12 +38,12 @@ export const getCommits = ({
     const base = getBaseCommit(sourceBranchCommit, targetBranchCommit);
     const commitsStrings = spawnCommandInGhWorkspace(`git log --pretty=format:'${GIT_LOG_FORMAT}' ${base.sha}..${sourceBranchCommit.sha}`)
         .split('\n');
-    const commits = JSON.parse(`[${commitsStrings.join(',')}]`) as Commit[];
-    commits.reverse();
+    const commitsJsons = commitsStrings.map((commitString) => parseCommitAsJson(commitString)) as Commit[];
```
Comment (oklinov) [inline bin/git.ts]: I'd call it just `commits` and `parseCommit`. When I see `somethingJson` it may indicate that it's json formatted string instead of plain JS object
```suggestion
    const commits = commitsStrings.map((commitString) => parseCommit(commitString)) as Commit[];
```

File: bin/git.ts [hunk 4]
```diff
@@ -1,11 +1,12 @@
...
+import { parseCommitAsJson, spawnCommandInGhWorkspace } from './utils.js';
 
-const GIT_LOG_FORMAT = `{"sha":"%H","author":"%aN<%aE>","date":"%aD","message":"%s"}`;
+const GIT_LOG_FORMAT = `%H»¦«%aN<%aE>»¦«%aD»¦«%s`;
 
 export const getBranchLastCommit = (branch: string): Commit => {
-    const lastCommit = JSON.parse(spawnCommandInGhWorkspace(`git log -1 --pretty=format:'${GIT_LOG_FORMAT}' ${branch}`)) as Commit;
-    return lastCommit;
+    const stringFormattedCommit = spawnCommandInGhWorkspace(`git log -1 --pretty=format:'${GIT_LOG_FORMAT}' ${branch}`);
+    const jsonParsedCommit = parseCommitAsJson(stringFormattedCommit);
```
Comment (oklinov) [inline bin/git.ts]: same as bellow :arrow_down: - I wouldn't use 'json' in vars names:
```suggestion
    const lastCommit = parseCommit(stringFormattedCommit);
```

File: bin/git.ts [hunk 5]
```diff
@@ -52,5 +53,7 @@ export const getBaseCommit = (target: Commit, source: Commit): Commit => {
 };
 
 export const getCommitInfo = (commitSha: string): Commit => {
-    return JSON.parse(spawnCommandInGhWorkspace(`git log -1 --pretty=format:'${GIT_LOG_FORMAT}' ${commitSha}`));
+    const stringParsedCommit = spawnCommandInGhWorkspace(`git log -1 --pretty=format:'${GIT_LOG_FORMAT}' ${commitSha}`);
+    const jsonParsedCommit = parseCommitAsJson(stringParsedCommit);
+    return jsonParsedCommit;
```
Comment (oklinov) [inline bin/git.ts]:
```suggestion
    const stringCommit = spawnCommandInGhWorkspace(`git log -1 --pretty=format:'${GIT_LOG_FORMAT}' ${commitSha}`);
    const commit = parseCommit(stringParsedCommit);
    return commit;
```

File: bin/utils.ts [hunk 6]
```diff
@@ -86,6 +87,19 @@ export const getHeadCommitSha = (githubEvent: GitHubEvent) => {
...
+    const [sha, author, date, message] = commitString.split('»¦«');
+    if (!sha || !author || !date || !message) {
```
Comment (oklinov) [inline bin/utils.ts]: According to chatgpt, some of these may be empty:

> ✅ So in short:
> Always non-empty: %H, %aD
> Can be empty: %aN, %aE, %s

so maybe it'd be safer to check the length:
```ts
const splits = commitString.split('»¦«');
if (splits.length !== 4) { ... }
const [sha, author, date, message] = splits;

**Review by oklinov — COMMENTED** [review]
thanks, overall good. just found couple of details :slightly_smiling_face: 

could you also write some unit tests for the commit parsing?

File: bin/git.ts (hunk 2 above)
Comment (ruocco-l) [reply bin/git.ts]: Smart

File: bin/utils.ts (hunk 6 above)
Comment (ruocco-l) [reply bin/utils.ts]: Yeah, I wasn't confident on this check right from the start. But maybe we want to allow the message to be empty?

Comment (oklinov) [reply bin/utils.ts]: yeah, I would allow it. Comparing `splits.length !== 4` will work also with an empty commit message. `.. || !message` would fail.

**Review by oklinov — APPROVED** [review]
